services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/var/www/html/docker-entrypoint-dev.sh"]
    environment:
      - SHELL=/bin/bash
    ports:
      - "0.0.0.0:3000:3000"  # Browser-sync with live reload
      - "0.0.0.0:8010:8010"  # PHP backend (optional, for debugging)
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
